

bool NOP() {
  //Mnemonic:  NOP
  //Assembled command: 0x00
  //Expected behavior: CPU performs no operation, PC advances
  //Test methodology: Run a NOP until all 16 bits of the address space have been cycled through
  //Success criteria: Verify that the address bus reads one higher than prior to the execution of the instruction

  //Initialize some data
  bool error = false;
  byte data[] = { 0x0 };
  uint16_t curAddr = 0;
  int delayTime = 5;

  Serial.print(F("Testing NOP "));
  for (unsigned int i = 0; i < 65535; i++) {

    //This instruction only takes a single M1 cycle
    writeSingleInstruction(data, 1, 0, 0);

    //Wait for the refresh cycle to end
    while (!digitalReadFast(RFSH)) {
      delayMicroseconds(0.1);
    }

    //Read the address bus, delaying long enough for the address bus to settl out after the refresh
    curAddr = readAddressBus(delayTime);

    //Test if the address bus reads the expected value
    if (curAddr != i + 1) {
      error = true;
    }

    //Display progress
    if ((curAddr % 1000) == 0) {
      Serial.print(F("."));
    }
  }

  //Display status
  if (error) {
    Serial.println(F("Fail"));
  } else {
    Serial.println(F("Pass"));
  }
}
bool LD_A_N() {}
bool LD_B_N() {}
bool LD_C_N() {}
bool LD_D_N() {}
bool LD_E_N() {}
bool LD_H_N() {}
bool LD_L_N() {}
bool LD_PTR_HL_N() {}
bool LD_A_A() {}
bool LD_B_A() {}
bool LD_C_A() {}
bool LD_D_A() {}
bool LD_E_A() {}
bool LD_H_A() {}
bool LD_L_A() {}
bool LD_A_B() {}
bool LD_B_B() {}
bool LD_C_B() {}
bool LD_D_B() {}
bool LD_E_B() {}
bool LD_H_B() {}
bool LD_L_B() {}
bool LD_A_C() {}
bool LD_B_C() {}
bool LD_C_C() {}
bool LD_D_C() {}
bool LD_E_C() {}
bool LD_H_C() {}
bool LD_L_C() {}
bool LD_A_D() {}
bool LD_B_D() {}
bool LD_C_D() {}
bool LD_D_D() {}
bool LD_E_D() {}
bool LD_H_D() {}
bool LD_L_D() {}
bool LD_A_E() {}
bool LD_B_E() {}
bool LD_C_E() {}
bool LD_D_E() {}
bool LD_E_E() {}
bool LD_H_E() {}
bool LD_L_E() {}
bool LD_A_H() {}
bool LD_B_H() {}
bool LD_C_H() {}
bool LD_D_H() {}
bool LD_E_H() {}
bool LD_H_H() {}
bool LD_L_H() {}
bool LD_A_L() {}
bool LD_B_L() {}
bool LD_C_L() {}
bool LD_D_L() {}
bool LD_E_L() {}
bool LD_H_L() {}
bool LD_L_L() {}
bool LD_A_PTR_HL() {}
bool LD_B_PTR_HL() {}
bool LD_C_PTR_HL() {}
bool LD_D_PTR_HL() {}
bool LD_E_PTR_HL() {}
bool LD_H_PTR_HL() {}
bool LD_L_PTR_HL() {}
bool LD_PTR_HL_A() {}
bool LD_PTR_HL_B() {}
bool LD_PTR_HL_C() {}
bool LD_PTR_HL_D() {}
bool LD_PTR_HL_E() {}
bool LD_PTR_HL_H() {}
bool LD_PTR_HL_L() {}
bool LD_A_PTR_BC() {}
bool LD_A_PTR_DE() {}
bool LD_A_PTR_NN() {}
bool LD_PTR_NN_A() {}
bool LD_PTR_BC_A() {}
bool LD_PTR_DE_A() {}
bool LD_A_I() {}
bool LD_A_R() {}
bool LD_I_A() {}
bool LD_R_A() {}
bool LD_PTR_IX_PLUS_D_N() {}
bool LD_PTR_IY_PLUS_D_N() {}
bool LD_A_PTR_IX_PLUS_D() {}
bool LD_B_PTR_IX_PLUS_D() {}
bool LD_C_PTR_IX_PLUS_D() {}
bool LD_D_PTR_IX_PLUS_D() {}
bool LD_E_PTR_IX_PLUS_D() {}
bool LD_H_PTR_IX_PLUS_D() {}
bool LD_L_PTR_IX_PLUS_D() {}
bool LD_A_PTR_IY_PLUS_D() {}
bool LD_B_PTR_IY_PLUS_D() {}
bool LD_C_PTR_IY_PLUS_D() {}
bool LD_D_PTR_IY_PLUS_D() {}
bool LD_E_PTR_IY_PLUS_D() {}
bool LD_H_PTR_IY_PLUS_D() {}
bool LD_L_PTR_IY_PLUS_D() {}
bool LD_PTR_IX_PLUS_D_A() {}
bool LD_PTR_IX_PLUS_D_B() {}
bool LD_PTR_IX_PLUS_D_C() {}
bool LD_PTR_IX_PLUS_D_D() {}
bool LD_PTR_IX_PLUS_D_E() {}
bool LD_PTR_IX_PLUS_D_H() {}
bool LD_PTR_IX_PLUS_D_L() {}
bool LD_PTR_IY_PLUS_D_A() {}
bool LD_PTR_IY_PLUS_D_B() {}
bool LD_PTR_IY_PLUS_D_C() {}
bool LD_PTR_IY_PLUS_D_D() {}
bool LD_PTR_IY_PLUS_D_E() {}
bool LD_PTR_IY_PLUS_D_H() {}
bool LD_PTR_IY_PLUS_D_L() {}
bool LD_BC_NN() {}
bool LD_DE_NN() {}
bool LD_HL_NN() {}
bool LD_SP_NN() {}
bool LD_IX_NN() {}
bool LD_IY_NN() {}
bool LD_BC_PTR_NN() {}
bool LD_DE_PTR_NN() {}
bool LD_HL_PTR_NN() {}
bool LD_SP_PTR_NN() {}
bool LD_IX_PTR_NN() {}
bool LD_IY_PTR_NN() {}
bool LD_PTR_NN_BC() {}
bool LD_PTR_NN_DE() {}
bool LD_PTR_NN_HL() {}
bool LD_PTR_NN_SP() {}
bool LD_PTR_NN_IX() {}
bool LD_PTR_NN_IY() {}
bool LD_SP_HL() {}
bool LD_SP_IX() {}
bool LD_SP_IY() {}
bool POP_AF() {}
bool POP_BC() {}
bool POP_DE() {}
bool POP_HL() {}
bool POP_IX() {}
bool POP_IY() {}
bool PUSH_AF() {}
bool PUSH_BC() {}
bool PUSH_DE() {}
bool PUSH_HL() {}
bool PUSH_IX() {}
bool PUSH_IY() {}
bool EX_AF_AF_PRIME() {}
bool EXX() {}
bool EX_DE_HL() {}
bool EX_PTR_SP_HL() {}
bool EX_PTR_SP_IX() {}
bool EX_PTR_SP_IY() {}
bool LDI() {}
bool LDIR() {}
bool LDD() {}
bool LDDR() {}
bool CPI() {}
bool CPIR() {}
bool CPD() {}
bool CPDR() {}
bool ADD_A_A() {}
bool ADD_A_B() {}
bool ADD_A_C() {}
bool ADD_A_D() {}
bool ADD_A_E() {}
bool ADD_A_H() {}
bool ADD_A_L() {}
bool ADD_A_PTR_HL() {}
bool ADD_A_PTR_IX_PLUS_D() {}
bool ADD_A_PTR_IY_PLUS_D() {}
bool ADD_A_N() {}
bool ADC_A_A() {}
bool ADC_A_B() {}
bool ADC_A_C() {}
bool ADC_A_D() {}
bool ADC_A_E() {}
bool ADC_A_H() {}
bool ADC_A_L() {}
bool ADC_A_PTR_HL() {}
bool ADC_A_PTR_IX_PLUS_D() {}
bool ADC_A_PTR_IY_PLUS_D() {}
bool ADC_A_N() {}
bool SUB_A_A() {}
bool SUB_A_B() {}
bool SUB_A_C() {}
bool SUB_A_D() {}
bool SUB_A_E() {}
bool SUB_A_H() {}
bool SUB_A_L() {}
bool SUB_A_PTR_HL() {}
bool SUB_A_PTR_IX_PLUS_D() {}
bool SUB_A_PTR_IY_PLUS_D() {}
bool SUB_A_N() {}
bool SBC_A_A() {}
bool SBC_A_B() {}
bool SBC_A_C() {}
bool SBC_A_D() {}
bool SBC_A_E() {}
bool SBC_A_H() {}
bool SBC_A_L() {}
bool SBC_A_PTR_HL() {}
bool SBC_A_PTR_IX_PLUS_D() {}
bool SBC_A_PTR_IY_PLUS_D() {}
bool SBC_A_N() {}
bool AND_A() {}
bool AND_B() {}
bool AND_C() {}
bool AND_D() {}
bool AND_E() {}
bool AND_H() {}
bool AND_L() {}
bool AND_PTR_HL() {}
bool AND_PTR_IX_PLUS_D() {}
bool AND_PTR_IY_PLUS_D() {}
bool AND_N() {}
bool XOR_A() {}
bool XOR_B() {}
bool XOR_C() {}
bool XOR_D() {}
bool XOR_E() {}
bool XOR_H() {}
bool XOR_L() {}
bool XOR_PTR_HL() {}
bool XOR_PTR_IX_PLUS_D() {}
bool XOR_PTR_IY_PLUS_D() {}
bool XOR_N() {}
bool OR_A() {}
bool OR_B() {}
bool OR_C() {}
bool OR_D() {}
bool OR_E() {}
bool OR_H() {}
bool OR_L() {}
bool OR_PTR_HL() {}
bool OR_PTR_IX_PLUS_D() {}
bool OR_PTR_IY_PLUS_D() {}
bool OR_N() {}
bool CP_A() {}
bool CP_B() {}
bool CP_C() {}
bool CP_D() {}
bool CP_E() {}
bool CP_H() {}
bool CP_L() {}
bool CP_PTR_HL() {}
bool CP_PTR_IX_PLUS_D() {}
bool CP_PTR_IY_PLUS_D() {}
bool CP_N() {}
bool INC_A() {}
bool INC_B() {}
bool INC_C() {}
bool INC_D() {}
bool INC_E() {}
bool INC_H() {}
bool INC_L() {}
bool INC_PTR_HL() {}
bool INC_PTR_IX_PLUS_D() {}
bool INC_PTR_IY_PLUS_D() {}
bool DEC_A() {}
bool DEC_B() {}
bool DEC_C() {}
bool DEC_D() {}
bool DEC_E() {}
bool DEC_H() {}
bool DEC_L() {}
bool DEC_PTR_HL() {}
bool DEC_PTR_IX_PLUS_D() {}
bool DEC_PTR_IY_PLUS_D() {}
bool DAA() {}
bool CPL() {}
bool NEG() {}
bool CCF() {}
bool SCF() {}
bool ADD_HL_BC() {}
bool ADD_HL_DE() {}
bool ADD_HL_HL() {}
bool ADD_HL_SP() {}
bool ADD_IX_BC() {}
bool ADD_IX_DE() {}
bool ADD_IX_SP() {}
bool ADD_IX_IX() {}
bool ADD_IY_BC() {}
bool ADD_IY_DE() {}
bool ADD_IY_SP() {}
bool ADD_IY_IY() {}
bool ADC_HL_BC() {}
bool ADC_HL_DE() {}
bool ADC_HL_HL() {}
bool ADC_HL_SP() {}
bool SBC_HL_BC() {}
bool SBC_HL_DE() {}
bool SBC_HL_HL() {}
bool SBC_HL_SP() {}
bool INC_BC() {}
bool INC_DE() {}
bool INC_HL() {}
bool INC_SP() {}
bool INC_IX() {}
bool INC_IY() {}
bool DEC_BC() {}
bool DEC_DE() {}
bool DEC_HL() {}
bool DEC_SP() {}
bool DEC_IX() {}
bool DEC_IY() {}
bool RLC_A() {}
bool RLC_B() {}
bool RLC_C() {}
bool RLC_D() {}
bool RLC_E() {}
bool RLC_H() {}
bool RLC_L() {}
bool RLC_PTR_HL() {}
bool RLC_PTR_IX_PLUS_D() {}
bool RLC_PTR_IY_PLUS_D() {}
bool RRC_A() {}
bool RRC_B() {}
bool RRC_C() {}
bool RRC_D() {}
bool RRC_E() {}
bool RRC_H() {}
bool RRC_L() {}
bool RRC_PTR_HL() {}
bool RRC_PTR_IX_PLUS_D() {}
bool RRC_PTR_IY_PLUS_D() {}
bool RL_A() {}
bool RL_B() {}
bool RL_C() {}
bool RL_D() {}
bool RL_E() {}
bool RL_H() {}
bool RL_L() {}
bool RL_PTR_HL() {}
bool RL_PTR_IX_PLUS_D() {}
bool RL_PTR_IY_PLUS_D() {}
bool RR_A() {}
bool RR_B() {}
bool RR_C() {}
bool RR_D() {}
bool RR_E() {}
bool RR_H() {}
bool RR_L() {}
bool RR_PTR_HL() {}
bool RR_PTR_IX_PLUS_D() {}
bool RR_PTR_IY_PLUS_D() {}
bool SLA_A() {}
bool SLA_B() {}
bool SLA_C() {}
bool SLA_D() {}
bool SLA_E() {}
bool SLA_H() {}
bool SLA_L() {}
bool SLA_PTR_HL() {}
bool SLA_PTR_IX_PLUS_D() {}
bool SLA_PTR_IY_PLUS_D() {}
bool SRA_A() {}
bool SRA_B() {}
bool SRA_C() {}
bool SRA_D() {}
bool SRA_E() {}
bool SRA_H() {}
bool SRA_L() {}
bool SRA_PTR_HL() {}
bool SRA_PTR_IX_PLUS_D() {}
bool SRA_PTR_IY_PLUS_D() {}
bool SLL_A() {}
bool SLL_B() {}
bool SLL_C() {}
bool SLL_D() {}
bool SLL_E() {}
bool SLL_H() {}
bool SLL_L() {}
bool SLL_PTR_HL() {}
bool SLL_PTR_IX_PLUS_D() {}
bool SLL_PTR_IY_PLUS_D() {}
bool SRL_A() {}
bool SRL_B() {}
bool SRL_C() {}
bool SRL_D() {}
bool SRL_E() {}
bool SRL_H() {}
bool SRL_L() {}
bool SRL_PTR_HL() {}
bool SRL_PTR_IX_PLUS_D() {}
bool SRL_PTR_IY_PLUS_D() {}
bool RLD() {}
bool RRD() {}
bool RLCA() {}
bool RRCA() {}
bool RLA() {}
bool RRA() {}
bool BIT_0_A() {}
bool BIT_0_B() {}
bool BIT_0_C() {}
bool BIT_0_D() {}
bool BIT_0_E() {}
bool BIT_0_H() {}
bool BIT_0_L() {}
bool BIT_0_PTR_HL() {}
bool BIT_0_PTR_IX_PLUS_D() {}
bool BIT_0_PTR_IY_PLUS_D() {}
bool BIT_1_A() {}
bool BIT_1_B() {}
bool BIT_1_C() {}
bool BIT_1_D() {}
bool BIT_1_E() {}
bool BIT_1_H() {}
bool BIT_1_L() {}
bool BIT_1_PTR_HL() {}
bool BIT_1_PTR_IX_PLUS_D() {}
bool BIT_1_PTR_IY_PLUS_D() {}
bool BIT_2_A() {}
bool BIT_2_B() {}
bool BIT_2_C() {}
bool BIT_2_D() {}
bool BIT_2_E() {}
bool BIT_2_H() {}
bool BIT_2_L() {}
bool BIT_2_PTR_HL() {}
bool BIT_2_PTR_IX_PLUS_D() {}
bool BIT_2_PTR_IY_PLUS_D() {}
bool BIT_3_A() {}
bool BIT_3_B() {}
bool BIT_3_C() {}
bool BIT_3_D() {}
bool BIT_3_E() {}
bool BIT_3_H() {}
bool BIT_3_L() {}
bool BIT_3_PTR_HL() {}
bool BIT_3_PTR_IX_PLUS_D() {}
bool BIT_3_PTR_IY_PLUS_D() {}
bool BIT_4_A() {}
bool BIT_4_B() {}
bool BIT_4_C() {}
bool BIT_4_D() {}
bool BIT_4_E() {}
bool BIT_4_H() {}
bool BIT_4_L() {}
bool BIT_4_PTR_HL() {}
bool BIT_4_PTR_IX_PLUS_D() {}
bool BIT_4_PTR_IY_PLUS_D() {}
bool BIT_5_A() {}
bool BIT_5_B() {}
bool BIT_5_C() {}
bool BIT_5_D() {}
bool BIT_5_E() {}
bool BIT_5_H() {}
bool BIT_5_L() {}
bool BIT_5_PTR_HL() {}
bool BIT_5_PTR_IX_PLUS_D() {}
bool BIT_5_PTR_IY_PLUS_D() {}
bool BIT_6_A() {}
bool BIT_6_B() {}
bool BIT_6_C() {}
bool BIT_6_D() {}
bool BIT_6_E() {}
bool BIT_6_H() {}
bool BIT_6_L() {}
bool BIT_6_PTR_HL() {}
bool BIT_6_PTR_IX_PLUS_D() {}
bool BIT_6_PTR_IY_PLUS_D() {}
bool BIT_7_A() {}
bool BIT_7_B() {}
bool BIT_7_C() {}
bool BIT_7_D() {}
bool BIT_7_E() {}
bool BIT_7_H() {}
bool BIT_7_L() {}
bool BIT_7_PTR_HL() {}
bool BIT_7_PTR_IX_PLUS_D() {}
bool BIT_7_PTR_IY_PLUS_D() {}
bool RES_0_A() {}
bool RES_0_B() {}
bool RES_0_C() {}
bool RES_0_D() {}
bool RES_0_E() {}
bool RES_0_H() {}
bool RES_0_L() {}
bool RES_0_PTR_HL() {}
bool RES_0_PTR_IX_PLUS_D() {}
bool RES_0_PTR_IY_PLUS_D() {}
bool RES_1_A() {}
bool RES_1_B() {}
bool RES_1_C() {}
bool RES_1_D() {}
bool RES_1_E() {}
bool RES_1_H() {}
bool RES_1_L() {}
bool RES_1_PTR_HL() {}
bool RES_1_PTR_IX_PLUS_D() {}
bool RES_1_PTR_IY_PLUS_D() {}
bool RES_2_A() {}
bool RES_2_B() {}
bool RES_2_C() {}
bool RES_2_D() {}
bool RES_2_E() {}
bool RES_2_H() {}
bool RES_2_L() {}
bool RES_2_PTR_HL() {}
bool RES_2_PTR_IX_PLUS_D() {}
bool RES_2_PTR_IY_PLUS_D() {}
bool RES_3_A() {}
bool RES_3_B() {}
bool RES_3_C() {}
bool RES_3_D() {}
bool RES_3_E() {}
bool RES_3_H() {}
bool RES_3_L() {}
bool RES_3_PTR_HL() {}
bool RES_3_PTR_IX_PLUS_D() {}
bool RES_3_PTR_IY_PLUS_D() {}
bool RES_4_A() {}
bool RES_4_B() {}
bool RES_4_C() {}
bool RES_4_D() {}
bool RES_4_E() {}
bool RES_4_H() {}
bool RES_4_L() {}
bool RES_4_PTR_HL() {}
bool RES_4_PTR_IX_PLUS_D() {}
bool RES_4_PTR_IY_PLUS_D() {}
bool RES_5_A() {}
bool RES_5_B() {}
bool RES_5_C() {}
bool RES_5_D() {}
bool RES_5_E() {}
bool RES_5_H() {}
bool RES_5_L() {}
bool RES_5_PTR_HL() {}
bool RES_5_PTR_IX_PLUS_D() {}
bool RES_5_PTR_IY_PLUS_D() {}
bool RES_6_A() {}
bool RES_6_B() {}
bool RES_6_C() {}
bool RES_6_D() {}
bool RES_6_E() {}
bool RES_6_H() {}
bool RES_6_L() {}
bool RES_6_PTR_HL() {}
bool RES_6_PTR_IX_PLUS_D() {}
bool RES_6_PTR_IY_PLUS_D() {}
bool RES_7_A() {}
bool RES_7_B() {}
bool RES_7_C() {}
bool RES_7_D() {}
bool RES_7_E() {}
bool RES_7_H() {}
bool RES_7_L() {}
bool RES_7_PTR_HL() {}
bool RES_7_PTR_IX_PLUS_D() {}
bool RES_7_PTR_IY_PLUS_D() {}
bool SET_0_A() {}
bool SET_0_B() {}
bool SET_0_C() {}
bool SET_0_D() {}
bool SET_0_E() {}
bool SET_0_H() {}
bool SET_0_L() {}
bool SET_0_PTR_HL() {}
bool SET_0_PTR_IX_PLUS_D() {}
bool SET_0_PTR_IY_PLUS_D() {}
bool SET_1_A() {}
bool SET_1_B() {}
bool SET_1_C() {}
bool SET_1_D() {}
bool SET_1_E() {}
bool SET_1_H() {}
bool SET_1_L() {}
bool SET_1_PTR_HL() {}
bool SET_1_PTR_IX_PLUS_D() {}
bool SET_1_PTR_IY_PLUS_D() {}
bool SET_2_A() {}
bool SET_2_B() {}
bool SET_2_C() {}
bool SET_2_D() {}
bool SET_2_E() {}
bool SET_2_H() {}
bool SET_2_L() {}
bool SET_2_PTR_HL() {}
bool SET_2_PTR_IX_PLUS_D() {}
bool SET_2_PTR_IY_PLUS_D() {}
bool SET_3_A() {}
bool SET_3_B() {}
bool SET_3_C() {}
bool SET_3_D() {}
bool SET_3_E() {}
bool SET_3_H() {}
bool SET_3_L() {}
bool SET_3_PTR_HL() {}
bool SET_3_PTR_IX_PLUS_D() {}
bool SET_3_PTR_IY_PLUS_D() {}
bool SET_4_A() {}
bool SET_4_B() {}
bool SET_4_C() {}
bool SET_4_D() {}
bool SET_4_E() {}
bool SET_4_H() {}
bool SET_4_L() {}
bool SET_4_PTR_HL() {}
bool SET_4_PTR_IX_PLUS_D() {}
bool SET_4_PTR_IY_PLUS_D() {}
bool SET_5_A() {}
bool SET_5_B() {}
bool SET_5_C() {}
bool SET_5_D() {}
bool SET_5_E() {}
bool SET_5_H() {}
bool SET_5_L() {}
bool SET_5_PTR_HL() {}
bool SET_5_PTR_IX_PLUS_D() {}
bool SET_5_PTR_IY_PLUS_D() {}
bool SET_6_A() {}
bool SET_6_B() {}
bool SET_6_C() {}
bool SET_6_D() {}
bool SET_6_E() {}
bool SET_6_H() {}
bool SET_6_L() {}
bool SET_6_PTR_HL() {}
bool SET_6_PTR_IX_PLUS_D() {}
bool SET_6_PTR_IY_PLUS_D() {}
bool SET_7_A() {}
bool SET_7_B() {}
bool SET_7_C() {}
bool SET_7_D() {}
bool SET_7_E() {}
bool SET_7_H() {}
bool SET_7_L() {}
bool SET_7_PTR_HL() {}
bool SET_7_PTR_IX_PLUS_D() {}
bool SET_7_PTR_IY_PLUS_D() {}
bool JP_NN() {}
bool JP_C_NN() {}
bool JP_NC_NN() {}
bool JP_Z_NN() {}
bool JP_NZ_NN() {}
bool JP_PE_NN() {}
bool JP_PO_NN() {}
bool JP_M_NN() {}
bool JP_P_NN() {}
bool JR_E() {}
bool JR_C_E() {}
bool JR_NC_E() {}
bool JR_Z_E() {}
bool JR_NZ_E() {}
bool JP_PTR_HL() {}
bool JP_PTR_IX() {}
bool JP_PTR_IY() {}
bool CALL_NN() {}
bool CALL_C_NN() {}
bool CALL_NC_NN() {}
bool CALL_Z_NN() {}
bool CALL_NZ_NN() {}
bool CALL_PE_NN() {}
bool CALL_PO_NN() {}
bool CALL_M_NN() {}
bool CALL_P_NN() {}
bool DJNZ_E() {}
bool RET() {}
bool RET_C() {}
bool RET_NC() {}
bool RET_Z() {}
bool RET_NZ() {}
bool RET_PE() {}
bool RET_PO() {}
bool RET_M() {}
bool RET_P() {}
bool RET_I() {}
bool RET_N() {}
bool RST_0() {}
bool RST_8() {}
bool RST_16() {}
bool RST_24() {}
bool RST_32() {}
bool RST_40() {}
bool RST_48() {}
bool RST_56() {}
bool IN_A_PTR_N() {}
bool IN_A_PTR_C() {}
bool IN_B_PTR_C() {}
bool IN_C_PTR_C() {}
bool IN_D_PTR_C() {}
bool IN_E_PTR_C() {}
bool IN_H_PTR_C() {}
bool IN_L_PTR_C() {}
bool INI() {}
bool INIR() {}
bool IND() {}
bool INDR() {}
bool OUT_PTR_N_A() {}
bool OUT_PTR_C_A() {}
bool OUT_PTR_C_B() {}
bool OUT_PTR_C_C() {}
bool OUT_PTR_C_D() {}
bool OUT_PTR_C_E() {}
bool OUT_PTR_C_H() {}
bool OUT_PTR_C_L() {}
bool OUTI() {}
bool OUTIR() {}
bool OUTD() {}
bool OUTDR() {}
bool HALT_() {}
bool DI() {}
bool EI() {}
bool IM0() {}
bool IM1() {}
bool IM2() {}
